name: Redstone duplication bug.
description: There is a way to duplicate redstone using available craft and gringers from tech mods.
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug.
            description: A clear and concise description of what the bug is.
            value: There is a way to duplicate redstone using available craft and gringers from tech mods.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1. Craft "Raw Redstone Block" using 4 "Redstone".
                2. Put "Raw Redstone Block" in "Grinder" and get 8 "redstone" or do the same with "Industrial grinder" or "Macerator"
                3. Repeat process.
                ...
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
            value: Attached to pull request.
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report or Log
            description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue
        validations:
            required: false
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            value: Windows 10
        validations:
            required: true
    -   type: input
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            value: "Prominence II 1.20.1"
        validations:
            required: true
    -   type: input
        attributes:
            label: Modloader
            description: The version of Minecraft you were using when the bug occured
            value: "Fabric"
        validations:
            required: true
    -   type: input
        attributes:
            label: Modpack Version
            description: The Modpack version you where using example bmc v52
            value: "Prominence || RPG v3.0.21"
        validations:
            required: true
    -   type: input
        attributes:
            label: Optifine
            description: Did you used Optifine in our packs?
            value: "No"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Any other mods you added to our packs? if yes please list any other mods.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this bug report and to help improve Better Minecraft"
