name: Bug Report
description: Create a bug report to help us improve Prominence
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
            value: Players will lost items in cosmetic slots after death and retrieving item from graves.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1. Wear two hats, one in normal slot and the other in cosmetic slot
                2. use /kill to kill yourself
                3. pick up items from your grave, then open inventory and you will find that your hat in cosmetic slot is missing
                ...
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Solution
            description: If applicable, add screenshots or videos to help explain your problem
            value: I have talked to the Creator of You're in grave danger, and he said this issue can be fixed by updating the mod to the newest version!
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report or Log
            description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue
        validations:
            required: false
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            value: Windows 11
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            value: 1.20.1
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Modloader
            description: The version of Minecraft you were using when the bug occured
            value:
                - "Fabric"
        validations:
            required: true
    -   type: input
        attributes:
            label: Modpack Version
            description: The Modpack version you where using example bmc v52
            value: Prominence II RPG v3.0.21
        validations:
            required: true
    -   type: input
        attributes:
            label: Optifine
            description: Did you used Optifine in our packs?
            value:
                - "No"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Any other mods you added to our packs? if yes please list any other mods.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this bug report and to help improve Better Minecraft"
